---
- hosts: demo
  user: usuarioconacceso
  sudo: yes
  tasks:

  - name: Creamos el grupo 'ansible' si no existe
    group:
      name: ansible
      state: present

  - name: A単adimos el grupo 'ansible' a sudoers sin necesidad de contrase単a
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%ansible'
      line: '%ansible ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: A単adir usuario 'ansrunner' al grupo 'ansible'
    user: name=ansrunner groups=ansible append=yes state=present createhome=yes

  - name: A単adir la clave rsa al usuario 'ansrunner'

    authorized_key:
      user: ansrunner
      state: present
      key: "{{ lookup('file', '/home/miusuario/.ssh/id_rsa.pub') }}"