---
- hosts: demo
  user: root
  
  tasks:
  ##
  # Instalacion de paquetes necesarios
  ##
  - name: General | Instalacion de paquetes requeridos
  action : apt pkg={{ item }} state=installed
  with_items:
    - php5
	- apache2
	- mysql-server
	- mysql-client
	- php5-mysql
	- php-apc
	- php5-xmlrpc
	- php-soap
	- php5-gd
	- unzip
	- python-mysqldb
  
  ##
  # Configuracion de Apache2
  ##
  - name: Apache2 | Habilitar modulos
  action: command a2enmod rewrite vhost_alias
  
  ##
  # Reinicio de servicios
  ##
  - name: Restart Apache2
    action: service name=apache2 state=restarted